---
- name: Clone Sculpin from GitHub.
  git:
    repo: https://github.com/sculpin/sculpin.git
    dest: "{{ sculpin_install_path }}"
    version: "{{ sculpin_version }}"
    update: no

- name: Install Sculpin with Composer.
  shell: >
    {{ composer_path }} update --prefer-source --no-interaction
    chdir={{ sculpin_install_path }}
    creates={{ sculpin_install_path }}/vendor/autoload.php

- name: Create Sculpin symlink.
  sudo: yes
  file:
    src: "{{ sculpin_install_path }}/bin/sculpin"
    dest: "{{ sculpin_path }}"
    state: link
