---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install PHP packages.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ sculpin_php_packages }}"

- name: Download Sculpin.
  sudo: yes
  get_url:
    url: https://download.sculpin.io/sculpin.phar
    dest: '{{ sculpin_path }}'

- name: Set permissions for Sculpin.
  file:
    path: '{{ sculpin_path }}'
    mode: 775